### ISSUE TITLE
Could not authenticate

### ISSUE THREAD

**Issue by Kambonde** [tmpethick/campusnet-electron#11]
I have a  recurring problem: When I try to log in it says "Could not authenticate". When I try with mail instead of student number, it says username and password does not match, so I'm out of ideas for where the error occurs.

**Comment by tmpethick** [comment]
I've send the people responsible for the API a mail asking if anything has changed. Thanks for letting me know! Unfortunately there is not a lot I can do right now.

**Comment by Kambonde** [comment]
Don't know what caused the change, but it finally logged in today. :)
