### ISSUE TITLE
Problem with the website.

### ISSUE THREAD

**Issue by Bubbi12** [tmpethick/campusnet-electron#2]
Hi mate,
Thank you for the project. However, it looks like it is not syncing because of the link to campusnet is broken.

**Comment by tmpethick** [comment]
Thanks for letting me know, I'm planning on looking into it at some point this week 👍

**Comment by s163951** [comment]
anything new?

**Comment by tmpethick** [comment]
I had some troubles spinning up the dev environment but luckily DTU have now fixed their issue (they had moved the url and deprecated the old). I might push a new version with some fixes now that I have the workflow up again – but don't hold me responsible ;)
