### ISSUE TITLE
What is CampusNet?! 

### ISSUE THREAD

**Issue by OliverFlecke** [tmpethick/campusnet-electron#4]
Please change name to Inside

**Comment by tmpethick** [comment]
Our team is working on it.

**Comment by tmpethick** [comment]
Your prayers have been answered: https://github.com/tmpethick/campusnet-electron/issues/6#issuecomment-365928910.

**Comment by OliverFlecke** [comment]
Thanks for fixing this very disturbing and disruptive bug!
