### ISSUE TITLE
Sync stopped - then folderchanging was blocked

### ISSUE THREAD

**Issue by askf0123** [tmpethick/campusnet-electron#8]
Hi, the app stopped syncing up about a week ago, so I tried changing the sync-to-folder. Then it started working again, but suddenly I wasn't able to change back to the old directory. I tried restarting the app, then pc and also reinstalled the app with no success. Apparently, it remembered the sync-to-folder when I reinstalled the app. Hope you can help me out, I really appreciate this sync-service!

Regards
Ask

**Comment by askf0123** [comment]
Apparently the problem is that i can't sync to folders within my onedrive.
I can sync to new folder on the desktop etc. but i tried within the
onedrive with  no succes.

2018-04-16 12:21 GMT+02:00 Thomas Pethick <notifications@github.com>:

**Comment by tmpethick** [comment]
Hmm it sounds like onedrive might add a hidden file within the folder that would prevent it. Do you get the warning saying that the folder is not empty?

Maybe we should consider removing the check. After all files would only be overwritten if a folder with a course name existed inside the folder already.

**Comment by askf0123** [comment]
No error occures, and the directory just does'nt change.

Den 16. apr. 2018 2.58 PM skrev "Thomas Pethick" <notifications@github.com>:

Hmm it sounds like onedrive might add a hidden file within the folder that
would prevent it. Do you get the warning saying that the folder is not
empty?

Maybe we should consider removing the check. After all files would only be
overwritten if a folder with a course name existed inside the folder
already.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmpethick/campusnet-electron/issues/8#issuecomment-381590085>,
or mute the thread

**Comment by askf0123** [comment]
But previously it has been syncing to onedrive just fine

Den man. d. 16. apr. 2018 18.32 skrev Ask Finderup <ask.finderup@gmail.com>:

**Comment by askf0123** [comment]
Do you have any suggestions?

Den man. d. 16. apr. 2018 18.33 skrev Ask Finderup <ask.finderup@gmail.com>:

**Comment by tmpethick** [comment]
And you have tried syncing to an empty folder within onedrive?

Right now I don't have any easy way to debug it, but I'll keep the issue open to when I have time to have a look at it. If you learn anything new, please do share!

**Comment by askf0123** [comment]
Yeah, tried creating a new folder within onedrive, but it did'nt work. I'll
tell if i find out something. Thank you

Den fre. d. 20. apr. 2018 11.40 skrev Thomas Pethick <
notifications@github.com>:

**Comment by askf0123** [comment]
Hi, now it's working again.

Kind regards
Ask FInderup

Den fre. 20. apr. 2018 kl. 11.44 skrev Ask Finderup <ask.finderup@gmail.com
