### ISSUE TITLE
Is not able to open on mac

### ISSUE THREAD

**Issue by simonelnahas** [tmpethick/campusnet-electron#9]

**Comment by s163951** [comment]
Check with the developer to make sure CampusNetSync works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.

Click Report to see more detailed information and send a report to Apple

**Comment by s163951** [comment]
Reinstallation doesn't work

**Comment by s163951** [comment]
when running as developer `npm start` : 
`*** WARNING: Textured window <AtomNSWindow: 0x7fe957d93300> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.`

**Comment by Kambonde** [comment]
I have the same problem. When I tried to run the app, I got an error saying I should reinstall the app, but now when I try to open the dmg file it says it can't be opened and I should move it to trash.

**Comment by s163951** [comment]
Yes it depends on if you open the file being saved to /Applications or not

**Comment by tmpethick** [comment]
Thanks for the debugging! Unfortunately I don't have much time this week to
have a look at it, but will squeeze in time the following. Good to hear
people are using it!

**Comment by s163951** [comment]
I see people using it everywhere here at DTU ;)

**Comment by tmpethick** [comment]
@s163951  *Polite bump* ;) ..  I've tried a fix now – could you see whether it works for you? And if not check whether "System Events" is checked for CampusNetSync under "System Preferences -> Security & Privacy -> Privacy -> Automation".

**Comment by Kambonde** [comment]
It works perfectly again - Thank you so much! :)

**Comment by tmpethick** [comment]
Great! Please spread the word - let it be known wide and far that
campusnetsync now works again!

**Comment by simonelnahas** [comment]
I will! Hurray
